name: Publish to NPM

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run pack
      - run: npm run test:headless:singleRun
      - run: cp README.md ./src/lib/dist/README.md
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: './src/lib/dist/package.json'
