name: Run CI Tests

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm run test
